// Curatela fantacalcistica 2026/27 (stime pre-asta, da rifinire con il listone ufficiale).
// tier: forza della squadra (1 = top, 5 = lotta salvezza)
// xi: titolari fissi attesi · bal: ballottaggi · rig: [1°, 2°] rigorista · pun: punizioni · cor: corner
// qt: quotazioni stimate (scala Qt.A, budget 500) per i giocatori chiave · role: override ruolo classic
export const CURATION = {
  inter: {
    tier: 1,
    xi: ['Josep Martínez', 'Manuel Akanji', 'Alessandro Bastoni', 'John Stones', 'Djed Spence', 'Federico Dimarco', 'Nicolò Barella', 'Hakan Çalhanoğlu', 'Petar Sučić', 'Lautaro Martínez', 'Marcus Thuram'],
    bal: ['Yann Bisseck', 'Luis Henrique', 'Piotr Zieliński', 'Henrikh Mkhitaryan', 'Francesco Pio Esposito', 'Ange-Yoan Bonny', 'Carlos Augusto', 'Benjamin Pavard'],
    rig: ['Hakan Çalhanoğlu', 'Lautaro Martínez'], pun: ['Federico Dimarco', 'Hakan Çalhanoğlu'], cor: ['Hakan Çalhanoğlu', 'Federico Dimarco'],
    qt: { 'Lautaro Martínez': 40, 'Marcus Thuram': 30, 'Hakan Çalhanoğlu': 18, 'Nicolò Barella': 15, 'Federico Dimarco': 22, 'Alessandro Bastoni': 15, 'Manuel Akanji': 12, 'Josep Martínez': 18, 'Francesco Pio Esposito': 16, 'Ange-Yoan Bonny': 13, 'Petar Sučić': 12, 'Piotr Zieliński': 9, 'Yann Bisseck': 10, 'Djed Spence': 9, 'Henrikh Mkhitaryan': 8, 'Luis Henrique': 7, 'Ivan Provedel': 3 },
    role: { 'Luis Henrique': 'C', 'Carlos Augusto': 'D' },
  },
  napoli: {
    tier: 1,
    xi: ['Vanja Milinković-Savić', 'Giovanni Di Lorenzo', 'Amir Rrahmani', 'Alessandro Buongiorno', 'Mathías Olivera', 'Stanislav Lobotka', 'Frank Anguissa', 'Scott McTominay', 'Kevin De Bruyne', 'Matteo Politano', 'Rasmus Højlund'],
    bal: ['Alex Meret', 'Sam Beukema', 'Leonardo Spinazzola', 'David Neres', 'Noa Lang', 'Lorenzo Lucca', 'Billy Gilmour', 'Luca Marianucci'],
    rig: ['Kevin De Bruyne', 'Rasmus Højlund'], pun: ['Kevin De Bruyne', 'Matteo Politano'], cor: ['Kevin De Bruyne', 'Matteo Politano'],
    qt: { 'Rasmus Højlund': 32, 'Scott McTominay': 26, 'Kevin De Bruyne': 24, 'Vanja Milinković-Savić': 17, 'Giovanni Di Lorenzo': 14, 'Alessandro Buongiorno': 11, 'Amir Rrahmani': 9, 'Mathías Olivera': 9, 'Frank Anguissa': 12, 'Matteo Politano': 13, 'David Neres': 13, 'Noa Lang': 14, 'Lorenzo Lucca': 12, 'Stanislav Lobotka': 8, 'Sam Beukema': 8, 'Leonardo Spinazzola': 7, 'Alex Meret': 5 },
  },
  juventus: {
    tier: 1,
    xi: ['Guglielmo Vicario', 'Pierre Kalulu', 'Bremer', 'Lloyd Kelly', 'Andrea Cambiaso', 'Manuel Locatelli', 'Khéphren Thuram', 'Weston McKennie', 'Francisco Conceição', 'Kenan Yıldız', 'Nick Woltemade'],
    bal: ['Federico Gatti', 'Randal Kolo Muani', 'Edon Zhegrova', 'Teun Koopmeiners', 'Pape Matar Sarr', 'Juan Cabal', 'Zeki Çelik', 'Jérémie Boga'],
    rig: ['Kenan Yıldız', 'Manuel Locatelli'], pun: ['Kenan Yıldız', 'Teun Koopmeiners'], cor: ['Teun Koopmeiners', 'Francisco Conceição'],
    qt: { 'Kenan Yıldız': 30, 'Nick Woltemade': 24, 'Randal Kolo Muani': 18, 'Francisco Conceição': 16, 'Edon Zhegrova': 15, 'Andrea Cambiaso': 13, 'Bremer': 12, 'Pierre Kalulu': 10, 'Lloyd Kelly': 9, 'Federico Gatti': 9, 'Guglielmo Vicario': 16, 'Weston McKennie': 10, 'Teun Koopmeiners': 12, 'Manuel Locatelli': 9, 'Khéphren Thuram': 9, 'Arkadiusz Milik': 6 },
  },
  milan: {
    tier: 1,
    xi: ['Mike Maignan', 'Fikayo Tomori', 'Matteo Gabbia', 'Strahinja Pavlović', 'Alexis Saelemaekers', 'Pervis Estupiñán', 'Luka Modrić', 'Adrien Rabiot', 'Ardon Jashari', 'Christian Pulisic', 'Gonçalo Ramos'],
    bal: ['Mario Gila', 'Koni De Winter', 'Davide Bartesaghi', 'Ruben Loftus-Cheek', 'Omari Hutchinson', 'Yunus Musah', 'Samuel Chukwueze', 'Francesco Camarda'],
    rig: ['Christian Pulisic', 'Gonçalo Ramos'], pun: ['Christian Pulisic', 'Luka Modrić'], cor: ['Luka Modrić', 'Christian Pulisic'],
    qt: { 'Christian Pulisic': 30, 'Gonçalo Ramos': 22, 'Mike Maignan': 22, 'Adrien Rabiot': 15, 'Luka Modrić': 12, 'Ruben Loftus-Cheek': 10, 'Alexis Saelemaekers': 10, 'Strahinja Pavlović': 10, 'Fikayo Tomori': 8, 'Matteo Gabbia': 8, 'Pervis Estupiñán': 9, 'Davide Bartesaghi': 7, 'Omari Hutchinson': 12, 'Ardon Jashari': 8, 'Mario Gila': 8, 'Francesco Camarda': 7 },
  },
  como: {
    tier: 2,
    xi: ['Robert Sánchez', 'Ivan Smolčić', 'Trevoh Chalobah', 'Jacobo Ramón', 'Álex Valle', 'Máximo Perrone', 'Samuele Ricci', 'Jesús Rodríguez', 'Nico Paz', 'Assane Diao', 'Moise Kean'],
    bal: ['Jean Butez', 'Marc-Oliver Kempf', 'Yan Couto', 'Maxence Caqueret', 'Martin Baturina', 'Lucas Da Cunha', 'Anastasios Douvikas', 'Jayden Addai'],
    rig: ['Nico Paz', 'Moise Kean'], pun: ['Nico Paz', 'Martin Baturina'], cor: ['Nico Paz', 'Álex Valle'],
    qt: { 'Nico Paz': 28, 'Moise Kean': 30, 'Jesús Rodríguez': 14, 'Assane Diao': 13, 'Anastasios Douvikas': 12, 'Martin Baturina': 12, 'Robert Sánchez': 15, 'Álex Valle': 10, 'Jacobo Ramón': 8, 'Ivan Smolčić': 8, 'Trevoh Chalobah': 9, 'Máximo Perrone': 8, 'Samuele Ricci': 7, 'Jean Butez': 5 },
  },
  roma: {
    tier: 2,
    xi: ['Mile Svilar', 'Gianluca Mancini', 'Evan Ndicka', 'Konstantinos Koulierakis', 'Wesley', 'Nahuel Molina', 'Manu Koné', 'Marten de Roon', 'Matías Soulé', 'Paulo Dybala', 'Donyell Malen'],
    bal: ['Mario Hermoso', 'Daniele Ghilardi', 'Devyne Rensch', 'Bryan Cristante', 'Lorenzo Pellegrini', 'Santiago Castro', 'Niccolò Pisilli', 'Leonardo Balerdi'],
    rig: ['Paulo Dybala', 'Lorenzo Pellegrini'], pun: ['Paulo Dybala', 'Matías Soulé'], cor: ['Matías Soulé', 'Lorenzo Pellegrini'],
    qt: { 'Donyell Malen': 24, 'Paulo Dybala': 18, 'Matías Soulé': 18, 'Santiago Castro': 14, 'Mile Svilar': 22, 'Wesley': 12, 'Gianluca Mancini': 12, 'Evan Ndicka': 11, 'Manu Koné': 10, 'Lorenzo Pellegrini': 12, 'Nahuel Molina': 9, 'Konstantinos Koulierakis': 8, 'Marten de Roon': 7, 'Bryan Cristante': 7, 'Mario Hermoso': 7 },
    role: { 'Wesley': 'D' },
  },
  atalanta: {
    tier: 2,
    xi: ['Marco Carnesecchi', 'Odilon Kossounou', 'Isak Hien', 'Giorgio Scalvini', 'Raoul Bellanova', 'Davide Zappacosta', 'Éderson', 'Franck Kessié', 'Charles De Ketelaere', 'Giacomo Raspadori', 'Gianluca Scamacca'],
    bal: ['Sead Kolašinac', 'Lorenzo Bernasconi', 'Mario Pašalić', 'Lazar Samardžić', 'Kamaldeen Sulemana', 'Nikola Krstović', 'Nicola Zalewski', 'Eljif Elmas'],
    rig: ['Giacomo Raspadori', 'Charles De Ketelaere'], pun: ['Lazar Samardžić', 'Giacomo Raspadori'], cor: ['Charles De Ketelaere', 'Nicola Zalewski'],
    qt: { 'Gianluca Scamacca': 22, 'Charles De Ketelaere': 20, 'Giacomo Raspadori': 18, 'Nikola Krstović': 18, 'Marco Carnesecchi': 16, 'Éderson': 12, 'Mario Pašalić': 10, 'Lazar Samardžić': 9, 'Davide Zappacosta': 9, 'Raoul Bellanova': 9, 'Odilon Kossounou': 10, 'Isak Hien': 10, 'Giorgio Scalvini': 9, 'Kamaldeen Sulemana': 9, 'Franck Kessié': 8, 'Nicola Zalewski': 8 },
    role: { 'Charles De Ketelaere': 'A' },
  },
  bologna: {
    tier: 3,
    xi: ['Łukasz Skorupski', 'Emil Holm', 'Torbjørn Heggem', 'Martin Vitík', 'Juan Miranda', 'Lewis Ferguson', 'Nikola Moro', 'Riccardo Orsolini', 'Jens Odgaard', 'Nicolò Cambiaghi', 'Artem Dovbyk'],
    bal: ['Nicolò Casale', 'Nadir Zortea', 'Arthur Theate', 'Tommaso Pobega', 'Federico Bernardeschi', 'Roberto Piccoli', 'Oussama El Azzouzi', 'Samuel Mbangula'],
    rig: ['Riccardo Orsolini', 'Artem Dovbyk'], pun: ['Riccardo Orsolini', 'Federico Bernardeschi'], cor: ['Riccardo Orsolini', 'Juan Miranda'],
    qt: { 'Riccardo Orsolini': 22, 'Artem Dovbyk': 18, 'Roberto Piccoli': 12, 'Lewis Ferguson': 12, 'Jens Odgaard': 12, 'Łukasz Skorupski': 12, 'Nicolò Cambiaghi': 10, 'Federico Bernardeschi': 9, 'Juan Miranda': 9, 'Emil Holm': 9, 'Nadir Zortea': 7, 'Torbjørn Heggem': 7, 'Martin Vitík': 6 },
  },
  lazio: {
    tier: 3,
    xi: ['Christos Mandas', 'Adam Marušić', 'Josip Šutalo', 'Danilho Doekhi', 'Nuno Tavares', 'Kenneth Taylor', 'Nicolò Rovella', 'Davide Frattesi', 'Gustav Isaksen', 'Andrea Pinamonti', 'Mattia Zaccagni'],
    bal: ['Oliver Provstgaard', 'Diogo Leite', 'Luca Pellegrini', 'Manuel Lazzari', 'Fisayo Dele-Bashiru', 'Danilo Cataldi', 'Tijjani Noslin', 'Albert Guðmundsson', 'Matteo Cancellieri'],
    rig: ['Mattia Zaccagni', 'Andrea Pinamonti'], pun: ['Albert Guðmundsson', 'Mattia Zaccagni'], cor: ['Mattia Zaccagni', 'Albert Guðmundsson'],
    qt: { 'Mattia Zaccagni': 18, 'Andrea Pinamonti': 16, 'Albert Guðmundsson': 14, 'Gustav Isaksen': 12, 'Davide Frattesi': 12, 'Christos Mandas': 12, 'Nuno Tavares': 12, 'Kenneth Taylor': 9, 'Tijjani Noslin': 9, 'Adam Marušić': 7, 'Nicolò Rovella': 7, 'Matteo Cancellieri': 7 },
  },
  fiorentina: {
    tier: 3,
    xi: ['David de Gea', 'Dodô', 'Marin Pongračić', 'Radu Drăgușin', 'Fabiano Parisi', 'Nicolò Fagioli', 'Arthur Atta', 'Marco Brescianini', 'Franco Mastantuono', 'Beto', 'Pedro Gonçalves'],
    bal: ['Luca Ranieri', 'Wilfried Gnonto', 'Cher Ndour', 'Álex Jiménez', 'Mateo Pellegrino', 'Alieu Njie'],
    rig: ['Pedro Gonçalves', 'Beto'], pun: ['Nicolò Fagioli', 'Franco Mastantuono'], cor: ['Pedro Gonçalves', 'Nicolò Fagioli'],
    qt: { 'Pedro Gonçalves': 18, 'Franco Mastantuono': 16, 'Beto': 14, 'Mateo Pellegrino': 11, 'Wilfried Gnonto': 9, 'David de Gea': 15, 'Dodô': 11, 'Nicolò Fagioli': 10, 'Fabiano Parisi': 8, 'Marin Pongračić': 7, 'Luca Ranieri': 7 },
  },
  torino: {
    tier: 4,
    xi: ['Franco Israel', 'Nathan Patterson', 'Saúl Coco', 'Ardian Ismajli', 'Cristiano Biraghi', 'Cesare Casadei', 'Emirhan İlkhan', 'Nikola Vlašić', 'Zakaria Aboukhlal', 'Giovanni Simeone', 'Duván Zapata'],
    bal: ['Lucas Perri', 'Pietro Comuzzo', 'Ricardo Rodriguez', 'Rafik Belghali', 'Rolando Mandragora', 'Gvidas Gineitis', 'Ché Adams', 'Sandro Kulenović'],
    rig: ['Nikola Vlašić', 'Giovanni Simeone'], pun: ['Nikola Vlašić', 'Cristiano Biraghi'], cor: ['Cristiano Biraghi', 'Nikola Vlašić'],
    qt: { 'Giovanni Simeone': 13, 'Duván Zapata': 12, 'Ché Adams': 11, 'Nikola Vlašić': 14, 'Zakaria Aboukhlal': 9, 'Cesare Casadei': 9, 'Franco Israel': 8, 'Cristiano Biraghi': 7, 'Saúl Coco': 6 },
  },
  udinese: {
    tier: 4,
    xi: ['Maduka Okoye', 'Oumar Solet', 'Christian Kabasele', 'Nicolò Bertola', 'Alessandro Zanoli', 'Hassane Kamara', 'Jesper Karlström', 'Sandi Lovrić', 'Jurgen Ekkelenkamp', 'Nicolò Zaniolo', 'Keinan Davis'],
    bal: ['David Alaba', 'Matteo Palma', 'Lennon Miller', 'Oier Zarraga', 'Vakoun Bayo', 'Idrissa Gueye', 'Jakub Piotrowski', 'Enzo Ebosse'],
    rig: ['Keinan Davis', 'Nicolò Zaniolo'], pun: ['Sandi Lovrić', 'Nicolò Zaniolo'], cor: ['Sandi Lovrić', 'Oier Zarraga'],
    qt: { 'Keinan Davis': 15, 'Nicolò Zaniolo': 15, 'Vakoun Bayo': 9, 'Sandi Lovrić': 9, 'Jurgen Ekkelenkamp': 8, 'Maduka Okoye': 9, 'Oumar Solet': 8, 'Hassane Kamara': 7, 'Alessandro Zanoli': 7 },
  },
  genoa: {
    tier: 4,
    xi: ['Justin Bijlow', 'Alessandro Marcandalli', 'Leo Østigård', 'Johan Vásquez', 'Stefano Sabelli', 'Morten Frendrup', 'Djibril Sow', 'Mikael Egill Ellertsson', 'Tommaso Baldanzi', 'Vitinha', 'Lorenzo Colombo'],
    bal: ['Sebastian Otoa', 'Kingsley Ehizibue', 'Mario Mitaj', 'Júnior Messias', 'Lorenzo Venturino', 'Stephan El Shaarawy', 'Hamed Traorè', 'Milutin Osmajić'],
    rig: ['Lorenzo Colombo', 'Júnior Messias'], pun: ['Tommaso Baldanzi', 'Júnior Messias'], cor: ['Tommaso Baldanzi', 'Stefano Sabelli'],
    qt: { 'Lorenzo Colombo': 12, 'Vitinha': 12, 'Tommaso Baldanzi': 9, 'Júnior Messias': 8, 'Stephan El Shaarawy': 7, 'Justin Bijlow': 9, 'Johan Vásquez': 8, 'Morten Frendrup': 6 },
  },
  sassuolo: {
    tier: 4,
    xi: ['Arijanet Muric', 'Sebastian Walukiewicz', 'Jay Idzes', 'Fedde Leysen', 'Josh Doig', 'Kristian Thorstvedt', 'Nemanja Matić', 'Ismaël Koné', 'Domenico Berardi', 'Armand Laurienté', 'Sebastiano Esposito'],
    bal: ['Fali Candé', 'Duje Ćaleta-Car', 'Cas Odenthal', 'Luca Lipani', 'Cristian Volpato', 'Kieron Bowie', 'Nicholas Pierini', 'Daniel Boloca'],
    rig: ['Domenico Berardi', 'Armand Laurienté'], pun: ['Domenico Berardi', 'Armand Laurienté'], cor: ['Domenico Berardi', 'Armand Laurienté'],
    qt: { 'Domenico Berardi': 22, 'Armand Laurienté': 14, 'Sebastiano Esposito': 11, 'Kristian Thorstvedt': 9, 'Cristian Volpato': 8, 'Arijanet Muric': 9, 'Josh Doig': 9, 'Jay Idzes': 7, 'Ismaël Koné': 7 },
  },
  parma: {
    tier: 4,
    xi: ['Edoardo Corvi', 'Enrico Delprato', 'Mariano Troilo', 'Abdoulaye Ndiaye', 'Sascha Britschgi', 'Emanuele Valeri', 'Mandela Keita', 'Adrián Bernabé', 'Vincent Sierro', 'Pontus Almqvist', 'El Bilal Touré'],
    bal: ['Lautaro Valenti', 'Franco Carboni', 'Christian Ordóñez', 'Benjamin Cremaschi', 'Hans Nicolussi Caviglia', 'Matija Frigan', 'Ousmane Diallo', 'Giovanni Fabbian'],
    rig: ['Adrián Bernabé', 'El Bilal Touré'], pun: ['Adrián Bernabé', 'Emanuele Valeri'], cor: ['Adrián Bernabé', 'Emanuele Valeri'],
    qt: { 'El Bilal Touré': 12, 'Adrián Bernabé': 10, 'Pontus Almqvist': 9, 'Matija Frigan': 8, 'Emanuele Valeri': 8, 'Edoardo Corvi': 7, 'Enrico Delprato': 6, 'Giovanni Fabbian': 7 },
  },
  cagliari: {
    tier: 5,
    xi: ['Elia Caprile', 'Yukinari Sugawara', 'Yerry Mina', 'Juan Rodríguez', 'Riyad Idrissi', 'Michel Adopo', 'Harry Winks', 'Alessandro Deiola', 'Jacopo Fazzini', 'Daniel Maldini', 'Kevin Carlos'],
    bal: ['Zé Pedro', 'Adam Obert', 'Roberto Gagliardini', 'Mattia Felici', "M'Bala Nzola", 'Yael Trepy'],
    rig: ['Jacopo Fazzini', 'Kevin Carlos'], pun: ['Jacopo Fazzini', 'Daniel Maldini'], cor: ['Jacopo Fazzini', 'Riyad Idrissi'],
    qt: { 'Kevin Carlos': 10, 'Daniel Maldini': 10, "M'Bala Nzola": 8, 'Jacopo Fazzini': 10, 'Mattia Felici': 7, 'Elia Caprile': 12, 'Riyad Idrissi': 7, 'Yerry Mina': 6 },
  },
  lecce: {
    tier: 5,
    xi: ['Wladimiro Falcone', 'Danilo Veiga', 'Kialonda Gaspar', 'Tiago Gabriel', 'Antonino Gallo', 'Lassana Coulibaly', 'Mohamed Kaba', 'Medon Berisha', 'Santiago Pierotti', 'Nikola Štulić', "Konan N'Dri"],
    bal: ['Jamil Siebert', 'Corrie Ndaba', 'Youssef Maleh', 'Ivan Ilić', 'Omri Gandelman', 'Sadik Fofana', 'Joël Monteiro', 'Willem Geubbels'],
    rig: ['Nikola Štulić', 'Medon Berisha'], pun: ['Medon Berisha', 'Antonino Gallo'], cor: ['Antonino Gallo', 'Medon Berisha'],
    qt: { 'Nikola Štulić': 11, 'Santiago Pierotti': 8, "Konan N'Dri": 8, 'Medon Berisha': 9, 'Wladimiro Falcone': 10, 'Antonino Gallo': 8, 'Danilo Veiga': 6 },
  },
  monza: {
    tier: 5,
    xi: ['Noel Törnqvist', 'Lorenzo Lucchesi', 'Jan Ziółkowski', 'Andrea Carboni', 'Samuele Birindelli', 'Ricardo Mangas', 'Matteo Pessina', 'Leonardo Colombo', 'Andrea Colpani', 'Cyril Ngonge', 'Patrick Cutrone'],
    bal: ['Valentin Antov', 'Saba Goglichidze', 'Ebenezer Akinsanmiro', 'Omari Forson', 'Keita Baldé', 'Dany Mota', 'Patrick Ciurria', 'Michael Folorunsho'],
    rig: ['Matteo Pessina', 'Patrick Cutrone'], pun: ['Andrea Colpani', 'Matteo Pessina'], cor: ['Andrea Colpani', 'Patrick Ciurria'],
    qt: { 'Patrick Cutrone': 12, 'Andrea Colpani': 12, 'Cyril Ngonge': 10, 'Keita Baldé': 8, 'Dany Mota': 7, 'Matteo Pessina': 9, 'Michael Folorunsho': 8, 'Noel Törnqvist': 8, 'Ricardo Mangas': 7, 'Samuele Birindelli': 6 },
  },
  frosinone: {
    tier: 5,
    xi: ['Lorenzo Palmisani', 'Anthony Oyono', 'Ilario Monterisi', 'Kevin Akpoguma', 'Gabriele Bracaglia', 'Giacomo Calò', 'Florian Grillitsch', 'Ben Lhassine Kone', 'Farès Ghedjemis', 'Antonio Raimondo', 'Giorgi Kvernadze'],
    bal: ['Gabriele Calvani', 'Giorgio Cittadini', 'Aleksa Terzić', 'Romano Schmid', 'Alessio Zerbin', 'Daniel Bîrligea', 'Francesco Gelli', 'Tomáš Bobček'],
    rig: ['Antonio Raimondo', 'Giacomo Calò'], pun: ['Giacomo Calò', 'Romano Schmid'], cor: ['Giacomo Calò', 'Farès Ghedjemis'],
    qt: { 'Antonio Raimondo': 10, 'Farès Ghedjemis': 8, 'Giorgi Kvernadze': 8, 'Daniel Bîrligea': 7, 'Giacomo Calò': 7, 'Lorenzo Palmisani': 6 },
  },
  venezia: {
    tier: 5,
    xi: ['Filip Stanković', 'Joël Schingtienne', 'Juan Jesus', 'Armel Bella-Kotchap', 'Pasquale Mazzocchi', 'Ridgeciano Haps', 'Gianluca Busio', 'Simon Sohm', 'Alfred Duncan', 'John Yeboah', 'Andrea Adorante'],
    bal: ['Lorenzo Montipò', 'Antoine Hainaut', 'Bartol Franjić', 'Thierry Correia', 'Toma Bašić', 'Kike Pérez', 'Akor Adams', 'Albion Rrahmani'],
    rig: ['Gianluca Busio', 'Andrea Adorante'], pun: ['Gianluca Busio', 'John Yeboah'], cor: ['Gianluca Busio', 'Ridgeciano Haps'],
    qt: { 'Andrea Adorante': 10, 'John Yeboah': 9, 'Akor Adams': 8, 'Gianluca Busio': 9, 'Filip Stanković': 7, 'Ridgeciano Haps': 6, 'Pasquale Mazzocchi': 6 },
  },
};
